"""
Evaluator Agent (LLM #4)
────────────────────────
Performs *factual-consistency checking* (a.k.a. faithfulness evaluation):
  1. Decompose the generated answer into atomic claims.
  2. For each claim, check whether the source context supports, partially
     supports, doesn't mention, or contradicts it.
  3. Produce an overall consistency score and a per-claim breakdown.

This is inspired by the SAFE (Search-Augmented Factuality Evaluator) and
FActScore methodologies.
"""

from __future__ import annotations
import logging
import time

from config import EvaluatorConfig
from llm_client import LLMClient
from models import (
    RetrievedChunk,
    EvaluatorOutput,
    ClaimEvaluation,
    ClaimVerdict,
)

logger = logging.getLogger(__name__)

EVALUATOR_SYSTEM_PROMPT = """\
You are a Factual Consistency Evaluator.  You will receive:
  • An ANSWER generated by an AI assistant
  • The SOURCE CONTEXT that the answer was supposed to be based on

Your task:
1. Decompose the ANSWER into individual factual claims.
   - Skip opinions, hedging language ("I think"), and meta-statements.
   - Each claim should be a single, verifiable assertion.

2. For each claim, determine:
   - **verdict**: one of "supported", "partially_supported", "not_supported", "contradicted"
   - **supporting_evidence**: quote the relevant part of the source context (if any)
   - **reasoning**: brief explanation of your verdict

3. Compute an **overall_consistency_score** (0.0 – 1.0):
   - 1.0 = every claim is fully supported
   - 0.0 = every claim is contradicted or unsupported
   - Weight: supported=1.0, partially_supported=0.5, not_supported=0.0, contradicted=-0.5
     Then clamp to [0, 1].

4. Write a brief **summary** (2-3 sentences) of your overall assessment.

Return ONLY valid JSON:
{
  "claims": [
    {
      "claim": "...",
      "verdict": "supported",
      "supporting_evidence": "...",
      "reasoning": "..."
    }
  ],
  "overall_consistency_score": 0.85,
  "summary": "..."
}
"""


class EvaluatorAgent:
    def __init__(self, config: EvaluatorConfig, llm: LLMClient):
        self._config = config
        self._llm = llm

    def evaluate(
        self,
        answer: str,
        context_chunks: list[RetrievedChunk],
        query: str = "",
    ) -> EvaluatorOutput:
        t0 = time.perf_counter()

        if not answer.strip() or not context_chunks:
            return EvaluatorOutput(
                overall_consistency_score=0.0,
                is_reliable=False,
                claims=[],
                summary="No answer or no context to evaluate.",
                processing_time_ms=0.0,
            )

        # ── Build prompt ────────────────────────────────────────────
        context_text = self._format_context(context_chunks)
        user_prompt = (
            f"ANSWER:\n{answer}\n\n"
            f"SOURCE CONTEXT:\n{context_text}"
        )
        if query:
            user_prompt = f"ORIGINAL QUESTION:\n{query}\n\n" + user_prompt

        messages = [
            {"role": "system", "content": EVALUATOR_SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt},
        ]

        # ── Call LLM ────────────────────────────────────────────────
        result = self._llm.chat_json(
            messages=messages,
            model=self._config.model,
            temperature=self._config.temperature,
            max_tokens=self._config.max_tokens,
        )

        # ── Parse ───────────────────────────────────────────────────
        claims = self._parse_claims(result)
        raw_score = result.get("overall_consistency_score", self._compute_score(claims))
        score = float(max(0.0, min(1.0, raw_score)))
        summary = result.get("summary", "")

        elapsed = (time.perf_counter() - t0) * 1000
        is_reliable = score >= self._config.consistency_threshold

        logger.info(
            f"Evaluator: score={score:.2f}, reliable={is_reliable}, "
            f"{len(claims)} claims ({elapsed:.0f}ms)"
        )

        return EvaluatorOutput(
            overall_consistency_score=score,
            is_reliable=is_reliable,
            claims=claims,
            summary=summary,
            processing_time_ms=elapsed,
        )

    # ── Helpers ─────────────────────────────────────────────────────

    @staticmethod
    def _format_context(chunks: list[RetrievedChunk]) -> str:
        parts = []
        for i, c in enumerate(chunks, 1):
            parts.append(f"[{i}] {c.chunk.content}")
        return "\n\n".join(parts)

    @staticmethod
    def _parse_claims(data: dict) -> list[ClaimEvaluation]:
        results = []
        for item in data.get("claims", []):
            try:
                results.append(ClaimEvaluation(
                    claim=item["claim"],
                    verdict=ClaimVerdict(item.get("verdict", "not_supported")),
                    supporting_evidence=item.get("supporting_evidence", ""),
                    reasoning=item.get("reasoning", ""),
                ))
            except (KeyError, ValueError) as e:
                logger.warning(f"Skipping malformed claim: {e}")
        return results

    @staticmethod
    def _compute_score(claims: list[ClaimEvaluation]) -> float:
        """Fallback score computation if LLM doesn't return one."""
        if not claims:
            return 0.0
        weights = {
            ClaimVerdict.SUPPORTED: 1.0,
            ClaimVerdict.PARTIALLY_SUPPORTED: 0.5,
            ClaimVerdict.NOT_SUPPORTED: 0.0,
            ClaimVerdict.CONTRADICTED: -0.5,
        }
        total = sum(weights.get(c.verdict, 0.0) for c in claims)
        return max(0.0, min(1.0, total / len(claims)))